 export enum Secteur {

  PRIVES_SOUMIS_AU_CODE_DU_TRAVAIL_ET_A_LA_CONVENTION_COLLECTIVE_CADRE,

  PUBLIQUES,

  AGRICOLES,

  CLINIQUE_PRIVEES,

  INDUSTRIE_DE_LA_BONNETERIE_ET_DE_LA_CONFECTION,

  TEXTILE,

  ELECTRICITE_ET_DE_LELECTRONIQUE,

  BATIMENT_ET_TRAVAUX_PUBLICS,

  INDUSTRIE_LAITIERE,

  PATISSERIE,

  INDUSTRIE_DE_LA_PEINTURE,

  COMMERCE_DES_MATERIAUX_DE_CONSTRUCTION_DU_BOIS_ET_DES_PRODUITS_SIDERURGIQUES,

  FABRICANTS_DE_PRODUITS_DE_TOILETTE_ET_DE_PARFUMERIE,

  FABRICANTS_DE_PRODUITS_DENTRETIEN_ET_DINSECTICIDES,

  SAVONNERIES_RAFFINNERIES_ET_USINES_DEXTRACTION_DE_HUILE_DE_GRIGNONS,

  TEINTURERIES_ET_BLANCHISSERIES,

  INDUSTRIE_DE_CHAUSSURES_ET_DES_ARTICLES_CHAUSSANTS,

  INDUSTRIE_DES_MATERIAUX_DE_CONSTRUCTION,

  INDUSTRIE_DE_TRANSFORMATION_DU_PLASTIQUE,

  INDUSTRIE_DE_LIMPRIMERIE,

  COMMERCE_ET_DISTRIBUTION_DU_PETROLE ,

  TRANSFORMATION_DU_VERRE_ET_DE_LA_MIROITERIE,

  MECANIQUE_GENERALE_ET_STATIONS_DE_VENTE_DES_CARBURANTS,

  INDUSTRIES_DE_CONSERVES_ET_SEMICONSERVES_ALIMENTAIRES_ET_DE_CONDITIONNEMENT_DHUILES,

  PATES_ALIMENTAIRES_ET_COUSCOUS,

  MINOTERIES,

  BOULANGERIES,

  JARDINS_DENFANT_ET_CRECHES,

  TORREFACTION_DU_CAFE,

  PHARMACIES_DOFFICINES,

  HOTELS_CLASSES_TOURISTIQUES_ET_ETABLISSEMENTSSIMILAIRES,

  AGENCES_DE_VOYAGES,

  LOUEURS_DE_VEHICULES,

  ENSEIGNEMENT_PRIVE,

  INDUSTRIE_DU_BOIS_LIEGE_ET_AMEUBLEMENT,

  COMMERCE_DE_GROS_DEMIGROS_ET_DETAILS,

  USINES_DE_BOISSONS_GAZEUSES_NON_ALCOOLISEES,

  INDUSTRIES_ET_COMMERCE_DES_BOISSONS_ALCOOLISEES,

  CUIRS_ET_PEAUX,

  CONSTRUCTEURS_ET_CONCESSIONNAIRES_DE_VEHICULES_AUTOMOBILES,

  CONCESSIONNAIRES_DU_MATERIEL_AGRICOLE_ET_DE_GENIE_CIVIL,

  LA_PRESSE_ECRITE,

  SALLES_DE_PROJECTION_CINEMATOGRAPHIQUE,

  FONDERIES_METALLURGIE_ET_CONSTRUCTION_MECANIQUE,

  CONSTRUCTION_METALLIQUE,

  BANQUES,

  ASSURANCES,

  CAFES_BARS_RESTAURANT_ET_ETABLISSEMENTS_SIMILAIRES,

  REPARTITEURS_DE_MEDICAMANTS_EN_GROS_ET_DEMI_GROS,

  TRANSPORT_ROUTIER_DE_MARCHANDISES,

  ENTREPRISES_DE_GARDIENNAGE_DE_SECURITE_ET_DE_TRANSPORT_DE_FONDS,

  MANUTENTION_AUX_PORTS_MARITIMES_COMMERCIAUX_DE_TUNISIE,

  EXPLOSIFS,

  SALINES_DE_TUNISIE


}
